### ISSUE TITLE
MySQL8 incompatibilities: caching_sha2_password.so missing

### ISSUE THREAD

**Issue by guice** [bitnami/bitnami-docker-wordpress#214] opened 2020-02-12 05:46 UTC
Trying to use helm `stable/wordpress` but running into caching_sha2_password.so error.

```
MySQL command failed to run. Error: 
 ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

**Steps to reproduce the issue:**

1. Use a MySQL 8.x database
2. Attempt to connect using externalDb.

**Describe the results you received:**
```
MySQL command failed to run. Error: 
 ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Using DigitalOcean clusters, which _only_ support MySQL8. Making MariaDb and MySQL 5.7 not an option.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Installing using `helm` into Kubernetes Cluster withing DigitalOcean, connecting to a DO MySQL Cluster.

**Comment by javsalgar** [comment] 2020-02-12 15:21
Hi,

I was able to reproduce the issue with our MySQL 8.0 container. The mysql-client we are using is that of MariaDB. It is not very clear to me if it supports that plugin. I guess that you may be able to change the authentication mechanism in your server to native

https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

Would that work for you?

**Comment by guice** [comment] 2020-02-12 17:42
I'm afraid the access DigitalOcean gives us does not give us the ability to modify the user's authentication type.

**Comment by guice** [comment] 2020-02-12 22:03
Nor does DigitalOcean give an option to use any other MySQL database version, or MariaDB: 
<img width="786" alt="Screen Shot 2020-02-12 at 12 41 44 PM" src="https://user-images.githubusercontent.com/205378/74381375-86d26000-4da8-11ea-99d6-8c2183a25b63.png">

I feel this should be a priority to be fixed given the popularity of MySQL, and the fact 5.7 is nearing the end official support (Oct 2020).

**Comment by javsalgar** [comment] 2020-02-14 08:45
Thank you for reporting. We will evaluate it and consider it for future releases. As soon as there are more news, I will update this ticket.

**Comment by javsalgar** [comment] 2020-02-19 11:24
Hi,

Just a quick note to let you know that we released a new mysql-client that is compatible with caching_sha2_password. However, it looks like WordPress is still not compatible with caching_sha2_password. At least I was unable to make it work without setting mysql_native_password. 

Sources:

    - https://medium.com/@hkdb/wordpress-cant-connect-to-the-latest-mysql-8-x-server-33c4c43b05b7
    - https://jonathandesrosiers.com/2019/02/trouble-connecting-to-database-when-using-mysql-8-x/

I am afraid the WordPress developers will need to add support for caching_sha2_password in order to make it work.

**Comment by guice** [comment] 2020-02-19 16:16
WP is working. I'm using their 7.4-fpm image successfully. But, I did have to use 7.4 version. I couldn't use 7.3 - there's apparently an issue in _php_ in 7.3 against MySQL8.

I built my own charts, and using `wordpress:php7.4-fpm-alpine` successfully with MySQL8.

**Comment by javsalgar** [comment] 2020-02-20 08:42
Question, weren't you able to create users in our database like this?

```
CREATE USER 'jeffrey'@'localhost'
  IDENTIFIED WITH mysql_native_password BY 'new_password'
```
With that you should be able to use WordPress with php 7.3

**Comment by guice** [comment] 2020-02-20 17:05
Honestly, I hadn't tried. I managed my user through DO's interface. 

Looking over some of DO's knowledge base articles, it does appear it would be possible to use native_password with users to get compatibility with older clients.

However, I'm a firm believer in moving forward - if sha2 is the route mysql8 is moving, it's a route third party clients should get working. As mentioned, I got it working using WP on php 7.4. I rather go that route, anyway.

**Comment by javsalgar** [comment] 2020-02-21 11:23
We are working on a major version of the WordPress container that will include non-root support. Among those changes, we will also change the PHP version to 7.4, which should make it compatible with caching_sha2_password. I will update this ticket when it is out.

**Comment by marcosbc** [comment] 2021-05-06 17:41
Closing this issue as it is not happening in new versions anymore. Make sure to use the latest version ([`5.7.1-debian-10-r21`](https://github.com/bitnami/bitnami-docker-wordpress#571-debian-10-r21)) if you find issues.

**Closed by marcosbc** 2021-05-06 17:41 UTC
Labels: on-hold
