### ISSUE TITLE
Use $_ENV for definitions loading in wp-config.php

### ISSUE THREAD

**Issue by polRk** [bitnami/bitnami-docker-wordpress#224] opened 2020-03-13 19:15 UTC
Can i add this code in **wp-config.php** ? 

```php
foreach ($_ENV as $key => $value) {
	$capitalized = strtoupper($key);
	if (!defined($capitalized)) {
		define($capitalized, $value);
	}
}
```

**Comment by polRk** [comment] 2020-03-13 21:02
I want to add plugin https://github.com/humanmade/S3-Uploads. I need modify wp-config.php

**Comment by juan131** [comment] 2020-03-16 08:15
Hi @polRk 

Thanks so much for the suggestion!

I'm closing this issue as a duplicate of https://github.com/bitnami/bitnami-docker-wordpress/issues/167

**Closed by juan131** 2020-03-16 08:15 UTC
