### ISSUE TITLE
Crash AH01909

### ISSUE THREAD

**Issue by scorpius81** [bitnami/bitnami-docker-wordpress#335] opened 2022-01-12 13:40 UTC
I tried to install both Wordpress and PhpMyadmin via HELM.
But in both cases it fails.
Here is the log
```console
$ kubectl logs  wordpress-956f8476-8mmjp -f -n website

wordpress 13:36:55.86 
wordpress 13:36:55.87 Welcome to the Bitnami wordpress container
wordpress 13:36:55.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 13:36:55.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 13:36:55.96 
wordpress 13:36:55.96 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 13:36:56.35 INFO  ==> Configuring the HTTP port
wordpress 13:36:56.46 INFO  ==> Configuring the HTTPS port
wordpress 13:36:56.65 INFO  ==> Configuring PHP options
wordpress 13:36:56.76 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 13:36:57.36 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 13:36:58.77 INFO  ==> Restoring persisted WordPress installation
wordpress 13:37:05.76 INFO  ==> Trying to connect to the database server
wordpress 13:37:13.01 INFO  ==> ** WordPress setup finished! **

wordpress 13:37:13.16 INFO  ==> ** Starting Apache **
[Wed Jan 12 13:37:13.661523 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.662228 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.960321 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.960888 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment] 2022-01-13 08:28
This is not an error but a warning provided by the web server (apache in this case) regarding the SSL certificate. The application should be up and running without any issue

```console
$ helm install wordpress bitnami/wordpress

$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
wordpress-66ff6c9b77-w7gl7   1/1     Running   0          117s
wordpress-mariadb-0          1/1     Running   0          117s

$ kubectl logs -f wordpress-66ff6c9b77-w7gl7
wordpress 08:25:36.33
wordpress 08:25:36.33 Welcome to the Bitnami wordpress container
wordpress 08:25:36.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 08:25:36.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 08:25:36.34
wordpress 08:25:36.35 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 08:25:36.40 INFO  ==> Configuring the HTTP port
wordpress 08:25:36.45 INFO  ==> Configuring the HTTPS port
wordpress 08:25:36.47 INFO  ==> Configuring PHP options
wordpress 08:25:36.49 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 08:25:36.59 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 08:25:36.75 INFO  ==> Ensuring WordPress directories exist
wordpress 08:25:36.75 INFO  ==> Trying to connect to the database server
wordpress 08:26:07.00 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 08:26:09.29 INFO  ==> Installing WordPress
wordpress 08:26:12.66 INFO  ==> Persisting WordPress installation
wordpress 08:26:16.40 INFO  ==> ** WordPress setup finished! **

wordpress 08:26:16.42 INFO  ==> ** Starting Apache **
[Thu Jan 13 08:26:16.796171 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 13 08:26:16.796734 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 13 08:26:16.835616 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 13 08:26:16.836075 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 13 08:26:16.905165 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Unix) OpenSSL/1.1.1d PHP/7.4.27 configured -- resuming normal operations
[Thu Jan 13 08:26:16.905248 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
10.30.3.1 - - [13/Jan/2022:08:26:17 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.1 - - [13/Jan/2022:08:26:27 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.1 - - [13/Jan/2022:08:26:37 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.1 - - [13/Jan/2022:08:26:47 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.1 - - [13/Jan/2022:08:26:57 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.1 - - [13/Jan/2022:08:27:07 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.26 - - [13/Jan/2022:08:27:17 +0000] "\x16\x03\x01\x02" 400 226
10.30.3.26 - - [13/Jan/2022:08:27:17 +0000] "\x16\x03\x01\x02" 400 226
10.30.3.1 - - [13/Jan/2022:08:27:17 +0000] "GET /wp-login.php HTTP/1.1" 200 6106
10.30.3.26 - - [13/Jan/2022:08:27:17 +0000] "POST /wp-cron.php?doing_wp_cron=1642062437.6008250713348388671875 HTTP/1.1" 200 -
```

Note the container in the main pod is showing in the stdout the logs from the Apache service, you should be able to see the HTTP requests (as well as any warning related to the webserver, but this is not an issue)

**Comment by scorpius81** [comment] 2022-01-13 11:48
The pods not ready

$ kubectl describe pod wppp-wordpress-5957c864b4-l5w4b -n website
Name:         wppp-wordpress-5957c864b4-l5w4b
Namespace:    website
Priority:     0
Node:         webfarm-k8s-worker2/192.168.200.15
Start Time:   Wed, 12 Jan 2022 14:01:16 +0000
Labels:       app.kubernetes.io/instance=wppp
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=wordpress
              helm.sh/chart=wordpress-12.3.1
              pod-template-hash=5957c864b4
Annotations:  cni.projectcalico.org/podIP: 10.244.4.104/32
              cni.projectcalico.org/podIPs: 10.244.4.104/32
Status:       Running
IP:           10.244.4.104
IPs:
  IP:           10.244.4.104
Controlled By:  ReplicaSet/wppp-wordpress-5957c864b4
Containers:
  wordpress:
    Container ID:   containerd://c9be27c7245ae1570e9f76717245e9d358ea89b9691bbb8a5634d579dc8881d0
    Image:          docker.io/bitnami/wordpress:5.8.3-debian-10-r0
    Image ID:       docker.io/bitnami/wordpress@sha256:5b5e7b0492a3b97a84af736993e437226ad81ed08dadb10294dcdd964498202d
    Ports:          8080/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    135
      Started:      Wed, 12 Jan 2022 21:59:40 +0000
      Finished:     Wed, 12 Jan 2022 21:59:44 +0000
    Ready:          False
    Restart Count:  97
    Requests:
      cpu:     300m
      memory:  512Mi
    Environment:
      BITNAMI_DEBUG:                          true
      ALLOW_EMPTY_PASSWORD:                   yes
      MARIADB_HOST:                           wppp-mariadb
      MARIADB_PORT_NUMBER:                    3306
      WORDPRESS_DATABASE_NAME:                bitnami_wordpress
      WORDPRESS_DATABASE_USER:                bn_wordpress
      WORDPRESS_DATABASE_PASSWORD:            <set to the key 'mariadb-password' in secret 'wppp-mariadb'>  Optional: false
      WORDPRESS_USERNAME:                     user
      WORDPRESS_PASSWORD:                     <set to the key 'wordpress-password' in secret 'wppp-wordpress'>  Optional: false
      WORDPRESS_EMAIL:                        user@example.com
      WORDPRESS_FIRST_NAME:                   FirstName
      WORDPRESS_LAST_NAME:                    LastName
      WORDPRESS_HTACCESS_OVERRIDE_NONE:       no
      WORDPRESS_ENABLE_HTACCESS_PERSISTENCE:  no
      WORDPRESS_BLOG_NAME:                    User's Blog!
      WORDPRESS_SKIP_BOOTSTRAP:               no
      WORDPRESS_TABLE_PREFIX:                 wp_
      WORDPRESS_SCHEME:                       http
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT:      
      WORDPRESS_AUTO_UPDATE_LEVEL:            none
      WORDPRESS_PLUGINS:                      none
      APACHE_HTTP_PORT_NUMBER:                8080
      APACHE_HTTPS_PORT_NUMBER:               8443
    Mounts:
      /bitnami/wordpress from wordpress-data (rw,path="wordpress")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gxbtf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  wordpress-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wppp-wordpress
    ReadOnly:   false
  kube-api-access-gxbtf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  2m36s (x2164 over 8h)  kubelet  Back-off restarting failed container

I can't access Wordpress

$ kubectl exec -n website -it wppp-wordpress-5957c864b4-l5w4b -- bash
I have no name!@wppp-wordpress-5957c864b4-l5w4b:/$ command terminated with exit code 137

I cant execute curl http://localhost:8080/wp-admin/install.php and curl http://localhost:8080/wp-login.php

Even if I install Phpmyadmin I have the same problem

**Comment by juan131** [comment] 2022-01-13 12:40
Duplicate of https://github.com/bitnami/charts/issues/8645

**Closed by juan131** 2022-01-13 12:40 UTC
