### ISSUE TITLE
Container WordPress closes without error message (Docker, Bitnami, MySQL)

### ISSUE THREAD

**Issue by DuerrundSteidle** [bitnami/bitnami-docker-wordpress#200] opened 2020-01-03 13:47 UTC
Hello together,

I have a problem creating containers. I want to use the console to create containers automatically. This works so far only it stops the container WordPress after a short time.

I guess the problem is related to MySQl because the automatic creation with MariaDB already worked. But with MySQL I can't get it to work.

The Container WordPress closes without any error message. The only message I got in Synology is that it closes. ( It is shown in the picture)

Would be great if someone could help me.

Greetings

```
version: '3.7'
  services:
  db:
    image: bitnami/mysql:latest
    volumes:
      - ./db
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - db
    ports:
      - 8000:80
      - 4000:443
    volumes:
      - ./wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=passowrd
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by juan131** [comment] 2020-01-03 15:02
Hi @DuerrundSteidle 

Thanks for reporting this issue. Some users reported the same issue in the repository below:

- https://github.com/bitnami-labs/aci-templates/issues/6

I guess you're facing an error like the one below in the WordPress logs:

```
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 1156 (08S01): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql//opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

It looks like we introduced some incompatibility with MySQL at some point in the MySQL client used in the WordPress image, and it's only compatible with MariaDB. 

We didn't notice it since we're testing this image with MariaDB in our daily tests. I created a task to investigate what's going on but we didn't have time to work on it yet. In the meantime, we recommend you to use the `bitnami/mariadb` image instead.

**Comment by DuerrundSteidle** [comment] 2020-01-03 20:02
Ok thanks for your very fast answer.

I think also it could be the same problem.

I will try to test the suggestion and looking forward to here from you when you solved the problem.

**Comment by sameersbn** [comment] 2020-01-06 09:02
@DuerrundSteidle Please note if using MariaDB is not an option, you could switch to the `bitnami/mysql:5.7` image

```yaml
version: '3.7'
services:
  db:
    image: bitnami/mysql:5.7
    volumes:
      - ./db
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - db
    ports:
      - 8000:80
      - 4000:443
    volumes:
      - ./wordpress
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DATABASE_USER=duerrundsteidle
      - WORDPRESS_DATABASE_NAME=duerrundsteidle
      - WORDPRESS_DATABASE_PASSWORD=duerrundsteidle
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by sameersbn** [comment] 2020-01-06 09:40
@DuerrundSteidle you may also want to take a look at my comment here https://github.com/bitnami-labs/aci-templates/issues/6#issuecomment-571070834

**Comment by DuerrundSteidle** [comment] 2020-01-08 19:43
Thanks for your answer I've tested it with the following code. And in the picture you can see the occured error.

[URL=https://www.bilder-upload.eu/bild-66ed72-1578512537.png.html](url)

version: '3.7'
services:
  db:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
     - db
    ports:
      - 8000:80
      - 4000:443
    environment:
      - MARIADB_HOST=db
      - MARIA_PORT_NUMBER=3306
      - MARIA_PORT_USER=root
      - MARIA_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./wordpress
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin

**Comment by juan131** [comment] 2020-01-09 08:33
I couldn't access the image @DuerrundSteidle 

Regarding your **docker-compose.yaml**, I'm missing the section @sameersbn suggested:

```yaml
    volumes:
      - 'mysql_data:/bitnami/mysql'
      - '/path/to/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
```

You're not mounting any custom MySql config file with the piece of configuration below:

```
[mysqld]
default_authentication_plugin=mysql_native_password
```

**Comment by DuerrundSteidle** [comment] 2020-01-10 14:49
[FirstError](https://www.bilder-upload.eu/bild-66ed72-1578512537.png.html)
Sry here is the picture again

Now I do what is written in this task
[Task](https://www.akamenskiy.com/fix-wordpress-database-connection-mysql-8/)

Now the following Error occured
[LastError](https://www.bilder-upload.eu/bild-69d77e-1578667659.png.html)

Could it be possible that I'm in the wrong folder?

Here is my code

```
version: '3.7'
services:
  mysql:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ' mysql_data:/bitnami/mysql'
      - '/path/to/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
     - mysql
    ports:
      - 8000:80
      - 4000:443
    environment:
      - MARIADB_HOST=mysql
      - MARIA_PORT_NUMBER=3306
      - MARIA_PORT_USER=root
      - MARIA_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./wordpress
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - ./phpmyadmin
```

**Comment by DuerrundSteidle** [comment] 2020-01-10 14:58
Additional I couldnt find any folder in opt is this normal?

[Folder](https://www.bilder-upload.eu/bild-8e79c4-1578668299.png.html)

**Comment by juan131** [comment] 2020-01-13 08:25
Hi @DuerrundSteidle 

The error you faced is related to your volumes structure. You added the piece below:

```yaml
services:
  mysql:
  ...
    volumes:
      - 'mysql_data:/bitnami/mysql'
```

However, you did not define the `mysql_data` volume. 

You have two options. Mount a local directory as you did for WordPress or PhpMyAdmin, or define the corresponding volume adding the block below at the end of your **docker-compose.yaml** (check how it's done at https://github.com/bitnami/bitnami-docker-wordpress/blob/master/docker-compose.yml):

```yaml
volumes:
  mariadb_data:
    driver: local
```

**Comment by DuerrundSteidle** [comment] 2020-01-15 12:30
Thanks for your answer. No I've tested uit with the following code and now there occur another error.
The error named:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mysql.volumes 'type' is a required property
services.phpmyadmin.volumes 'type' is a required property
services.wordpress.volumes 'type' is a required property`

And here the code
`version: '3.7'
services:
  mysql:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=duerrundsteidle
      - MYSQL_DATABASE=duerrundsteidle
      - MYSQL_USER=duerrundsteidle
      - MYSQL_PASSWORD=duerrundsteidle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data: /bitnami/mysql
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
     - mysql
    ports:
      - 8000:80
      - 4000:443
    environment:
      - MARIADB_HOST=mysql
      - MARIA_PORT_NUMBER=3306
      - MARIA_PORT_USER=root
      - MARIA_ROOT_PASSWORD=duerrundsteidle
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress_data: /bitnami/wordpress
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 12000:80
      - 14000:443
    volumes:
      - phpmyadmin_data: /bitnami/phpmyadmin
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
  phpmyadmin_data:
    driver: local`

**Comment by DuerrundSteidle** [comment] 2020-01-17 11:20
Oh thanks.

No I've tested ut another time and it creates me the 3 container. But the wordpress container still closes?
Do anyone of you know why?

[URL=https://www.bilder-upload.eu/bild-a91a7e-1579259995.png.html][IMG]https://www.bilder-upload.eu/thumb/a91a7e-1579259995.png[/IMG][/URL]

**Comment by juan131** [comment] 2020-01-20 08:13
Hi @DuerrundSteidle 

Could you please share the logs of the WordPress container? I am afraid I cannot diagnose what's going on without them.

**Comment by DuerrundSteidle** [comment] 2020-01-20 15:06
Ok where can I find the log?

In the docker Window/Protocol I can just see an entry for the starting of wordpress.

**Comment by juan131** [comment] 2020-01-21 09:10
Hi @DuerrundSteidle 

You can obtain any container log by running the command below:

```console
docker logs -f <CONTAINER>
```

or (if you're using docker-compose):

```console
docker-compose logs <CONTAINER>
```

More info: https://success.docker.com/article/view-realtime-container-logging

**Comment by DuerrundSteidle** [comment] 2020-01-21 09:30
Ok thanks.

I'm sorry but what did I wrong?

[Picture Error finding Log](https://www.bilder-upload.eu/bild-383458-1579598987.png.html)

**Comment by juan131** [comment] 2020-01-21 09:48
Hi @DuerrundSteidle 

You don't need to add the **greater than (>) or less than (<)** around the container name, so the final command should look like:

```console
$ docker logs -f laufzeitrechner_wordpress_1R
```

**Comment by DuerrundSteidle** [comment] 2020-01-21 09:57
Ok thanks here is the log

[Log Docker](https://www.bilder-upload.eu/bild-3d1986-1579600603.png.html)

**Comment by juan131** [comment] 2020-01-22 07:33
Hi @DuerrundSteidle 

As you can see in the logs, there are several lines which says `Connection with 'bn_wordpress' user is unsuccessful`. This indicate us there are issues with the credentials we're setting.

The problem is that you set the environment variables below in the **docker-compose.yaml**:

```yaml
      - WORDPRESS_DB_NAME=duerrundsteidle
      - WORDPRESS_DB_USER=duerrundsteidle
      - WORDPRESS_DB_PASSWORD=duerrundsteidle
```

However, those aren't recognised by WordPress as you can see in [this section](https://github.com/bitnami/bitnami-docker-wordpress#use-an-existing-database). You should be using the ones below instead:

```yaml
      - WORDPRESS_DATABASE_USER=duerrundsteidle
      - WORDPRESS_DATABASE_NAME=duerrundsteidle
      - WORDPRESS_DATABASE_PASSWORD=duerrundsteidle
```

**Comment by DuerrundSteidle** [comment] 2020-01-27 19:17
NOw it works! Thanks for all!

**Comment by juan131** [comment] 2020-01-28 08:08
Hi @DuerrundSteidle 

I'm glad you were able to solve it!! I proceed to close the issue as "solved'

Please feel free to reopen it if you require further assistance.

**Closed by juan131** 2020-01-28 08:08 UTC
